language: php

php:
  - 7.1
  - 7.2

services:
  - redis-server

branches:
  only:
    - master
    - development
    - /^feature\/.+$/
    - /^refactoring\/.+$/
    - /^issue\/.+$/

before_script:
 - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git checkout "$TRAVIS_BRANCH"; else git checkout -b "$TRAVIS_PULL_REQUEST_BRANCH"; fi
 - git reset --hard "$TRAVIS_COMMIT"
 - composer self-update
 - mkdir -p vendor/bin
 - mkdir -p build/logs
 - touch build/logs/phpmq.log
 - composer install -o --prefer-dist --no-interaction
 - echo 'extension = "redis.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
 - php vendor/bin/phpunit.phar -c build/

after_success:
 - travis_retry php vendor/bin/coveralls.phar -v --exclude-no-stmt
